# 속성

In [5]:
import numpy as np
arr = np.array([11, 22, 33, 44, 55])
arr.dtype

dtype('int32')

In [2]:
arr.shape # (행 렬)

(5,)

In [4]:
arr.size # 전체 데이터개수

5

# 형변환

In [10]:
arr = arr.astype(np.float32)


In [9]:
arr

array([11., 22., 33., 44., 55.], dtype=float32)

# reshape

In [13]:
arr2 = np.array( [1,2,3,4,5,6] )
arr2

array([1, 2, 3, 4, 5, 6])

In [14]:
arr2.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
arr2.reshape(-1, 3)
# -1을 넣으면 자동으로 행을 결정해줌 

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
arr2.reshape(3, -1)
# -1을 넣어서 열을 맞춰줌.

array([[1, 2],
       [3, 4],
       [5, 6]])

In [17]:
arr2.reshape(-1, 2, 3)

array([[[1, 2, 3],
        [4, 5, 6]]])

In [18]:
arr3 = np.array([[10,20,30], [100,200,300] ])
arr3.shape

(2, 3)

In [19]:
arr3.reshape(-1)

array([ 10,  20,  30, 100, 200, 300])

# Indexing Slicing

In [ ]:
# 인덱싱 : [인덱스넘버]
- 0 1 2 3 ...
- ... -3 -2 -1

In [20]:
arr = np.array( [11, 22, 33, 44, 55])
arr

array([11, 22, 33, 44, 55])

In [21]:
arr[0]

11

In [22]:
arr[-1]

55

In [23]:
arr[-2]

44

# 복수개 인덱싱

In [25]:
arr[ [0, 2, 3] ]

array([11, 33, 44])

# boolean 인덱싱

In [26]:
arr [ [ True, True, False, False, True]]


array([11, 22, 55])

## Slicing

- [ startIndex : endIndex : increament ]
- startIndex <= index < endIndex

In [28]:
arr[1:4:1]

array([22, 33, 44])

In [29]:
arr[1:4:2]

array([22, 44])

In [30]:
arr[1:4]

array([22, 33, 44])

In [31]:
arr[:4] # 0<= index < 4

array([11, 22, 33, 44])

In [32]:
arr[1:] # 1<= index <

array([22, 33, 44, 55])

In [33]:
arr[1:-1]

array([22, 33, 44])

In [37]:
arr[-1:-4:-1] # -1 <= index < -4   (-1, -2, -3)
arr[:-4:-1] # 증가치가 -1이면 -1이 생략,  증가치가 1이면 1이면 생략

array([11])

### 연산
- element wise (요소별 연산)
- 산술 관계 논리

In [46]:
my = [11, 22, 33, 44, 55]
# my+2 --> 연산 안됨

arr+2
# numpy는 연산됨 --> element wise

arr*2

# 연봉데이터 있을때 각연봉에 대한 
# 세금 3.3%을 제gks 실수령액을 구하시오

salary = np.array( [1000, 2000, 3000, 4000, 5000] )
salary = salary - (salary * 0.033);
salary = salary.astype(np.int32)
salary

array([ 967, 1934, 2901, 3868, 4835], dtype=int32)

### 관계연산자

arr > 30

In [54]:
arr[arr > 30]

array([33, 44, 55])

# 논리: and (&) , or (|), not(~)

In [57]:
arr[(arr == 22) | (arr == 44)]

array([22, 44])

In [59]:
arr[(arr > 20) & (arr < 40)]

array([22, 33])

In [61]:
arr[~(arr == 22)]

array([11, 33, 44, 55])

## 추가 수정 삭제 검색 정렬

### 추가

In [6]:
np.append(arr, [100, 200])

array([ 11,  22,  33,  44,  55, 100, 200])

수정

In [66]:
arr[0] = 100
arr

array([100,  22,  33,  44,  55])

In [76]:
arr[1:3] = [222,333]
print(arr)
arr[2:4] = arr[2:4] + 2

[100 222 333  44  55]


array([100, 222, 335,  46,  55])

In [89]:
# 30보다 데이터에 대해 기존값에 2를 더한 것으로 수정
arr = np.array([11, 22, 33, 44, 55])

arr[(arr>30)] = arr[(arr > 30)] + 2
arr

array([11, 22, 35, 46, 57])

# 삭제

In [93]:
arr = np.array([11, 22, 33, 44, 55])
arr = np.delete(arr, [1,3]) # 1, 3번째 인덱스에 해당하는 데이터 삭제 
arr

array([11, 33, 55])

In [100]:
arr = np.array([11, 22, 33, 44, 55])
arr = np.delete(arr, np.where(arr>=40))
print(arr)
np.__version__

[11 22 33]


'1.19.4'

# 정렬

In [103]:
arr = np.array([22, 11, 33, 44, 55])
arr = np.sort(arr)
print(arr)

# arg sort = index
arr = np.array([22, 11, 33, 44, 55])
arr = np.argsort(arr)
print(arr)

[11 22 33 44 55]
[1 0 2 3 4]


# 조건별 연산

In [107]:
# true 에 해당하는 인덱스에 할당
arr = np.array([11, 22, 33, 44, 55])
np.where(arr < 30, 'A', 'B')
np.where(arr < 30, arr+1, arr+2)

# 다중 조건이면 select
conList = [arr>50, arr>30, arr>=0]
choiceList = ['A', 'B', 'C', ]
arr = np.select(conList, choiceList)
print(arr)

['C' 'C' 'B' 'B' 'A']


### 통계
- ndarray의 멤버 함수
- np의 함수


In [122]:
arr = np.array([11, 22, 33, 44, 55])
print(arr.sum())
print("sum : ", np.sum(arr))
print("average : ",arr.mean())
print("max : ", arr.max())
print("arg max index : ", arr.argmax())
print("arr std : ", arr.std())
print("mediaum value : ", np.median(arr))
print("quantile : ", np.quantile(arr, [0.25, 0.5, 0.75]))

165
sum :  165
average :  33.0
max :  55
arg max index :  4
arr std :  15.556349186104045
mediaum value :  33.0
quantile :  [22. 33. 44.]


In [10]:
import numpy as np
kor = np.array([60, 55, 70, 30, 20, 90])
print(kor)
print("1. 국어점수가 가장 큰값 : ", kor.max())
print("2. 국어점수가 80점 이상인 값 : ", kor[kor>80])
print("3. 국어점수가 50점 이상 80점 이하: ", kor[(kor>= 50) & (kor<=80)])
print("4. 국어점수의 평균: ", round(kor.mean(), 2))
print("5. 국어점수의 총합: ", kor.sum())
print("6. 국어점수가 40점 이하인 데이터를 삭제: ", np.delete(kor, np.where(kor<=40)))

# kor[(kor>=50)] = kor[(kor>=50)] * 1.1)
print("7. 국어점수가 50점 이상인 데이터에 가산점 10%를 부여", np.where(kor>=50, kor*1.1, kor))

print("8. 국어점수 top5를 구하시오", np.sort(kor)[-1:-6:-1])

print("9. 국어점수가 70점 이상이면 '합격', 아니면 '불합격' 으로 출력하시오")
grade = np.where(kor >= 70, '합격', '불합격')
for n in zip(kor, grade):
    print(n)
    

[60 55 70 30 20 90]
1. 국어점수가 가장 큰값 :  90
2. 국어점수가 80점 이상인 값 :  [90]
3. 국어점수가 50점 이상 80점 이하:  [60 55 70]
4. 국어점수의 평균:  54.17
5. 국어점수의 총합:  325
6. 국어점수가 40점 이하인 데이터를 삭제:  [60 55 70 90]
7. 국어점수가 50점 이상인 데이터에 가산점 10%를 부여 [66.  60.5 77.  30.  20.  99. ]
8. 국어점수 top5를 구하시오 [90 70 60 55 30]
9. 국어점수가 70점 이상이면 '합격', 아니면 '불합격' 으로 출력하시오
(60, '불합격')
(55, '불합격')
(70, '합격')
(30, '불합격')
(20, '불합격')
(90, '합격')
