In [3]:
import numpy as np

In [2]:
import numpy as np
arr = np.array( [ [1,2,3],[7,5,2],[10,1,8],[6,3,4] ] )
arr

array([[ 1,  2,  3],
       [ 7,  5,  2],
       [10,  1,  8],
       [ 6,  3,  4]])

In [3]:
arr.shape

(4, 3)

In [5]:
arr.T

array([[ 1,  7, 10,  6],
       [ 2,  5,  1,  3],
       [ 3,  2,  8,  4]])

### 2차원 인덱싱 슬라이싱

### 인덱싱
- [행,열]
- [행]

In [ ]:
arr[1]

In [ ]:
arr[1,1]

In [4]:
print(arr)
arr[[0,2,3]]

[[ 1  2  3]
 [ 7  5  2]
 [10  1  8]
 [ 6  3  4]]


array([[ 1,  2,  3],
       [10,  1,  8],
       [ 6,  3,  4]])

### 슬라이싱

In [6]:
print(arr)
arr[1:]

[[ 1  2  3]
 [ 7  5  2]
 [10  1  8]
 [ 6  3  4]]


array([[ 7,  5,  2],
       [10,  1,  8],
       [ 6,  3,  4]])

In [11]:
arr[1:,[0,2]]

array([[ 7,  2],
       [10,  8],
       [ 6,  4]])

In [12]:
arr[1:,1:]

array([[5, 2],
       [1, 8],
       [3, 4]])

In [9]:
###마지막열을 제외하고 선택하시요.
print(arr)
arr[:,:-1] # 인공지능 특성데이터 추출

[[ 1  2  3]
 [ 7  5  2]
 [10  1  8]
 [ 6  3  4]]


array([[ 1,  2],
       [ 7,  5],
       [10,  1],
       [ 6,  3]])

In [11]:
arr[:,-1]

array([3, 2, 8, 4])

In [17]:
arr[:,[-1]] # 인공지능 라벨 추출시

array([[3],
       [2],
       [8],
       [4]])

### 2차원데이터 boolean indexing
- 행단위

In [18]:
arr[[True,False,False,True]]

array([[1, 2, 3],
       [6, 3, 4]])

### 연산

In [19]:
arr+2

array([[ 3,  4,  5],
       [ 9,  7,  4],
       [12,  3, 10],
       [ 8,  5,  6]])

In [20]:
arr*2

array([[ 2,  4,  6],
       [14, 10,  4],
       [20,  2, 16],
       [12,  6,  8]])

In [23]:
arr[1] = arr[1]+2

In [27]:
arr[:,1] = arr[:,1] +2 

In [14]:
print(arr)

print([arr[:,0]>5])

print(arr[ arr[:,0] > 5 ])

[[ 1  2  3]
 [ 7  5  2]
 [10  1  8]
 [ 6  3  4]]
[array([False,  True,  True,  True])]
[[ 7  5  2]
 [10  1  8]
 [ 6  3  4]]


#### 2차원 추가 수정 삭제 정렬

### 추가

In [34]:
ax = np.array( [[1,2],[3,4]])
ay = np.array( [[5,6],[7,8]])

In [35]:
np.append( ax, ay) # axis=None 1차원으로 계산

array([1, 2, 3, 4, 5, 6, 7, 8])

In [36]:
np.append( ax, ay, axis=0) #행으로 추가

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [40]:
np.vstack((ax,ay))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [37]:
np.append( ax, ay, axis=1) #열로 추가

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [41]:
np.hstack((ax,ay))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

### 삭제

In [42]:
np.delete( arr, [0,2] )

array([ 2,  7,  5,  2, 10,  1,  8,  6,  3,  4])

In [16]:
print(arr)
np.delete( arr, [0,2], axis=0 ) #행인덱스

[[ 1  2  3]
 [ 7  5  2]
 [10  1  8]
 [ 6  3  4]]


array([[7, 5, 2],
       [6, 3, 4]])

In [15]:
print(arr)
np.delete( arr, [0,2], axis=1 ) #컬럼인덱스

[[ 1  2  3]
 [ 7  5  2]
 [10  1  8]
 [ 6  3  4]]


array([[2],
       [5],
       [1],
       [3]])

#### 정렬

In [46]:
np.sort( arr , axis=None )

array([ 1,  1,  2,  2,  3,  3,  4,  5,  6,  7,  8, 10])

In [18]:
print(arr)
np.sort( arr , axis=0 ) #컬럼별 정렬

[[ 1  2  3]
 [ 7  5  2]
 [10  1  8]
 [ 6  3  4]]


array([[ 1,  1,  2],
       [ 6,  2,  3],
       [ 7,  3,  4],
       [10,  5,  8]])

In [17]:
print(arr)
np.sort( arr , axis=1 ) #행별 정렬

[[ 1  2  3]
 [ 7  5  2]
 [10  1  8]
 [ 6  3  4]]


array([[ 1,  2,  3],
       [ 2,  5,  7],
       [ 1,  8, 10],
       [ 3,  4,  6]])

2차원통계
- 디폴트 axis=None ==> 1차원의 통계
- axis=0 ==>컬럼별 통계값
- axis=1 => row별 통계값

In [51]:
arr.sum() # np.sum(arr)

52

In [52]:
arr.sum(axis=0) # np.sum(arr, axis=0)

array([24, 11, 17])

In [53]:
arr.sum(axis=1) # np.sum(arr, axis=1)

array([ 6, 14, 19, 13])

In [54]:
arr.mean()

4.333333333333333

In [55]:
arr.mean(axis=0)

array([6.  , 2.75, 4.25])

In [56]:
arr.mean(axis=1)

array([2.        , 4.66666667, 6.33333333, 4.33333333])

In [57]:
arr.max()

10

In [58]:
arr.max(axis=0)

array([10,  5,  8])

In [59]:
arr.argmax()

6

In [60]:
arr.argmax(axis=0)

array([2, 1, 2])

In [61]:
arr.argmax(axis=1) # ***** 인공지능 많이 사용

array([2, 0, 0, 0])

In [62]:
for n in arr:
    print( n )

[1 2 3]
[7 5 2]
[10  1  8]
[6 3 4]


In [63]:
for a,b,c in arr:
    print(a,b,c )

1 2 3
7 5 2
10 1 8
6 3 4


In [50]:
arr

array([[ 1,  2,  3],
       [ 7,  5,  2],
       [10,  1,  8],
       [ 6,  3,  4]])

In [49]:
arr = np.array( [ [1,2,3],[7,5,2],[10,1,8],[6,3,4] ] )
arr

array([[ 1,  2,  3],
       [ 7,  5,  2],
       [10,  1,  8],
       [ 6,  3,  4]])

In [7]:
birth = np.loadtxt('data/births.txt',delimiter=',', dtype=np.int64)
birth

array([[   1880,   90993,  110491],
       [   1881,   91954,  100745],
       [   1882,  107850,  113688],
       [   1883,  112321,  104629],
       [   1884,  129022,  114445],
       [   1885,  133055,  107800],
       [   1886,  144535,  110784],
       [   1887,  145982,  101414],
       [   1888,  178627,  120853],
       [   1889,  178366,  110584],
       [   1890,  190377,  111025],
       [   1891,  185482,  101196],
       [   1892,  212346,  122037],
       [   1893,  212906,  112317],
       [   1894,  222922,  115772],
       [   1895,  233630,  117398],
       [   1896,  237920,  119570],
       [   1897,  234202,  112758],
       [   1898,  258770,  122693],
       [   1899,  233023,  106212],
       [   1900,  299828,  150499],
       [   1901,  239348,  106471],
       [   1902,  264077,  122659],
       [   1903,  261973,  119234],
       [   1904,  275371,  128125],
       [   1905,  291629,  132319],
       [   1906,  295303,  133159],
       [   1907,  318566,  1

In [ ]:
미국에서 태어난 년도 ,남아수

In [65]:
birth.shape

(132, 3)