https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html

In [4]:
import pandas as pd
import numpy as np

d1 = [[1,2], [3,4], [5,6]]
d2 = ((1,2), (3,4), (5,6))
d3 = [{'kor':1, 'eng':2},
      {'kor':3, 'eng':4},
      {'kor':5, 'eng':6}]

d4 = {'kor':[1,3,5], 'eng':[2,4,6]}
d5 = [ pd.Series([1,2,3]), pd.Series([4,5,6]) ]

In [11]:
df = pd.DataFrame(d1, index=['a','b','c'], columns=['eng', 'kor'])
df

eng  kor
a    1    2
b    3    4
c    5    6

In [15]:
df = pd.DataFrame(d2, index=['a','b','c'], columns=['eng', 'kor'])
df


eng  kor
a    1    2
b    3    4
c    5    6

In [17]:
df = pd.DataFrame(d3)
df

kor  eng
0    1    2
1    3    4
2    5    6

In [18]:
df = pd.DataFrame(d4)
df

kor  eng
0    1    2
1    3    4
2    5    6

In [19]:
df = pd.DataFrame(d5)
df

0  1  2
0  1  2  3
1  4  5  6

In [2]:
import pandas as pd
import numpy as np

data = {'eng': [10,30,50,70],
        'kor': [20,40,60,80],
        'math': [90,50,20,70]}

df = pd.DataFrame(data, index=['a','b','c','d'])
print("차원 : ", df.ndim)
print("행/렬 : ", df.shape)
print("행의개수 : ", df.shape[0], len(df))
print("전체개수 : ", df.size)
print("TransPose 인덱스와 컬럼 체인지\n", df.T)
print("index : ", df.index)
print("values : numpy array", df.values)
print("type : ", df.dtypes)
print("one type : ", df.dtypes.loc['eng'])
print("info : ", df.info()) # 중요 ******
print("colums : ", df.columns, "type : ", type(df.columns))

차원 :  2
행/렬 :  (4, 3)
행의개수 :  4 4
전체개수 :  12
TransPose 인덱스와 컬럼 체인지
        a   b   c   d
eng   10  20  50  70
kor   20  40  60  80
math  90  50  20  70
index :  Index(['a', 'b', 'c', 'd'], dtype='object')
values : numpy array [[10 20 90]
 [20 40 50]
 [50 60 20]
 [70 80 70]]
type :  eng     int64
kor     int64
math    int64
dtype: object
one type :  int64
<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, a to d
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   eng     4 non-null      int64
 1   kor     4 non-null      int64
 2   math    4 non-null      int64
dtypes: int64(3)
memory usage: 300.0+ bytes
info :  None
colums :  Index(['eng', 'kor', 'math'], dtype='object') type :  <class 'pandas.core.indexes.base.Index'>


# 인덱스 슬라이싱
- [컬럼명]

In [52]:
# df['a']  #error
df['eng'] # columns 명 줘야됨.

a    10
b    20
c    50
d    70
Name: eng, dtype: int64

In [50]:
df['eng'].sum()

150

In [51]:
df['eng'].values

array([10, 20, 50, 70], dtype=int64)

In [53]:
df[['eng', 'math']]

eng  math
a   10    90
b   20    50
c   50    20
d   70    70

In [54]:
df[['eng']] # 복수개로 감싸면 dataFrame나옴

eng
a   10
b   20
c   50
d   70

In [57]:
df['eng'] # series

a    10
b    20
c    50
d    70
Name: eng, dtype: int64

## 슬라이싱
- zero base[시작인덱스 : 끝인덱스 : 증가치]
- 부여된 인덱스[시작인덱스 : 끝인덱스]

In [58]:
df[1:4] # zero base

eng  kor  math
b   20   40    50
c   50   60    20
d   70   80    70

In [63]:
df['b':'c'] # 부여된 인덱스

eng  kor  math
b   20   40    50
c   50   60    20

# iloc 속성
- zerobase 기준
- iloc(행,열)

In [65]:
df.iloc[0]

eng     10
kor     20
math    90
Name: a, dtype: int64

In [66]:
df.iloc[1,1]

40

In [71]:
df.iloc[1:]

eng  kor  math
b   20   40    50
c   50   60    20
d   70   80    70

In [72]:
df.iloc[1:, 1:]

kor  math
b   40    50
c   60    20
d   80    70

In [75]:
# 복수개의 행선택
df.iloc[ [2,3] ]

eng  kor  math
c   50   60    20
d   70   80    70

In [81]:
df.iloc[[1,2], [0,2]]

eng  math
b   20    50
c   50    20

### loc 속성
- 부여된 인덱스명, 부여된 컬럼명 기준
- loc[행, 렬]

In [88]:
df

eng  kor  math
a   10   20    90
b   20   40    50
c   50   60    20
d   70   80    70

In [85]:
arr = np.array([[1,2], [3,4], [5,6]])
arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [86]:
df.loc['b']

eng     20
kor     40
math    50
Name: b, dtype: int64

In [87]:
df.loc['b', 'kor']

40

In [92]:
df.loc['b':, 'kor':]

kor  math
b   40    50
c   60    20
d   80    70

In [93]:
df.loc[['b', 'd'] ]

eng  kor  math
b   20   40    50
d   70   80    70

In [3]:
df.loc[:, 'kor':]

kor  math
a   20    90
b   40    50
c   60    20
d   80    70

In [34]:
import pandas as pd
import numpy as np

data = {'eng': [10,30,50,70],
        'kor': [20,40,60,80],
        'math': [90,50,20,70]}

df = pd.DataFrame(data, index=['a','b','c','d'])

In [15]:
print(df)
df['eng'] = df['eng'] + 2
print(df)

   eng  kor  math
a   10   20    90
b   30   40    50
c   50   60    20
d   70   80    70
   eng  kor  math
a   12   20    90
b   32   40    50
c   52   60    20
d   72   80    70


In [20]:
df.loc['b'] = df.loc['b'] + 2
df

eng  kor  math
a   10   20    90
b   32   42    52
c   50   60    20
d   70   80    70

In [24]:
df.loc['b':'c', 'kor':] = df.loc['b':'c', 'kor':] + 2
df

eng  kor  math
a   10   20    90
b   30   42    52
c   50   62    22
d   70   80    70

# 데이터 검색 boolean indexing
- 행단위

In [25]:
df[[True, False, False, True]]


eng  kor  math
a   10   20    90
d   70   80    70

In [28]:
df[ df['eng'] > 30 ]

eng  kor  math
c   50   62    22
d   70   80    70

In [35]:
df[ (df['kor'] == 40) | (df['kor'] == 60) ]

eng  kor  math
b   30   40    50
c   50   60    20

In [38]:
df [(df['math'] >= 20) & (df['math'] <= 50)]

eng  kor  math
b   30   40    50
c   50   60    20

In [40]:
df[ df['kor'].isin([40,60]) ]

eng  kor  math
b   30   40    50
c   50   60    20

In [42]:
df[ df['math'].between(20, 50) ]

eng  kor  math
b   30   40    50
c   50   60    20

### query

In [45]:
import pandas as pd
import numpy as np

data = {'eng': [10,30,50,70],
        'kor': [20,40,60,80],
        'math': [90,50,20,70]}

df = pd.DataFrame(data, index=['a','b','c','d'])

In [49]:
df.query('kor>=40 or kor==60')

eng  kor  math
b   30   40    50
c   50   60    20
d   70   80    70

In [52]:
df [ (df['math'] >= 20) & (df['math']<=50) ]
df.query('math>=20 and math<=50')
df.query('20 <= math <= 50')

eng  kor  math
b   30   40    50
c   50   60    20

In [64]:
n = 40
df[ df['kor'] >= n]
# query case  
# '' 앞에 f 붙이고 변수 앞뒤로 {}붙임
df.query('kor >= %d' % n) # format 권장...
df.query('kor >= {0}'.format(n)) # format 권장...
df.query(f'kor >= {n}') # format 권장...
#df.query('kor>=@n') # 함수내에서만 사용

eng  kor  math
b   30   40    50
c   50   60    20
d   70   80    70

# 추가, 삭제, 정렬

In [162]:
import pandas as pd
import numpy as np

data = {'eng': [10,30,50,70],
        'kor': [20,40,60,80],
        'math': [90,50,20,70]}
df = pd.DataFrame(data, index = ['a','b','c','d'])


# Columns Add

In [73]:
df['eng'] = [1,2,3,4] # 수정
df['my'] = [1,2,3,4]  # 추가
df['my1'] = df['kor'] + df['math']
df

eng  kor  math  my  my1
a    1   20    90   1  110
b    2   40    50   2   90
c    3   60    20   3   80
d    4   80    70   4  150

# Row Add

### 컬럼 중간에 추가

In [98]:
# 행 중간에 추가는 XX
#df.insert(2, 'my', df['eng'])
#df.insert(1, 'my', [1,2,3,4])
df

eng  my  kor  math
a   10   1   20    90
b   30   2   40    50
c   50   3   60    20
d   70   4   80    70

In [81]:
# 컬럼이 아니니 행 일경우 loc 사용
df.loc['a'] = [1,2,3]
df.loc['e'] = [1,2,3]
df

eng  kor  math
a    1    2     3
b   30   40    50
c   50   60    20
d   70   80    70
e    1    2     3

# Delete

In [110]:
# df.drop(index=부여된인덱스명, columns=부여된컬럼명)
df.drop(index=['a','d'])
df.drop(columns=['eng','math'])
df.drop(columns=['eng','math'], inplace=True)
df

kor
a   20
b   40
c   60
d   80

In [133]:
# dataframe 국어점수가 50점 이상인 행을 삭제하시오
df[df['kor'] >= 50].index
df.query('kor >= 50').index
df.drop(index=df.query('kor >= 50').index)

eng  kor  math
a   10   20    90
b   30   40    50

# 결측데이터 처리
- 삭제
- 대표값 (평균, 중앙값 , 최빈값)

In [134]:
df

eng  kor  math
a   10   20    90
b   30   40    50
c   50   60    20
d   70   80    70

# nan 데이터 만들기

In [160]:
import pandas as pd
import numpy as np

data = {'eng': [10,30,50,70],
        'kor': [20,40,60,80],
        'math': [90,50,20,70]}

df = pd.DataFrame(data, index=['a','b','c','d'])

df.loc['b':'c', 'kor'] = np.nan
df.loc['c':'d', 'math'] = np.nan

df.isna().sum()

eng     0
kor     2
math    2
dtype: int64

# Nan 데이터 채우기


In [145]:
# 다채우기
df.fillna(1)

eng   kor  math
a   10  20.0  90.0
b   30   1.0  50.0
c   50   1.0   1.0
d   70  80.0   1.0

In [148]:
m = df['kor'].mean()
df['kor'].fillna(m, inplace=True)
df

eng   kor  math
a   10  20.0  90.0
b   30  50.0  50.0
c   50  50.0   NaN
d   70  80.0   NaN

# nan 데이터 삭제

In [149]:
df.dropna() # nan 행을 삭제

eng   kor  math
a   10  20.0  90.0
b   30  50.0  50.0

In [152]:
df.dropna(axis=1) # nan 컬럼을 삭제

eng   kor
a   10  20.0
b   30  50.0
c   50  50.0
d   70  80.0

In [159]:
# subset 행에서 Nan 데이터 행만 삭제
print(df)
print(df.dropna(subset=['kor']))

   eng   kor  math
a   10  20.0  90.0
b   30   NaN  50.0
c   50   NaN   NaN
d   70  80.0   NaN
   eng   kor  math
a   10  20.0  90.0
d   70  80.0   NaN


# Sort

In [173]:
import pandas as pd
import numpy as np

data = {'eng': [10,30,50,70],
        'kor': [20,40,60,80],
        'math': [90,50,20,70]}
df = pd.DataFrame(data, index = ['a','b','c','d'])

df.sort_values(by='math')

eng  kor  math
c   50   60    20
b   30   40    50
d   70   80    70
a   10   20    90

In [164]:
df.sort_values(by='math',ascending=False)

eng  kor  math
a   10   20    90
d   70   80    70
b   30   40    50
c   50   60    20

In [176]:
df.loc['c', 'kor'] = 40
print(df, '\n')
# kor 점수같은경우 math 비교해서 정렬
df = df.sort_values(by=['kor', 'math'])
print(df)


   eng  kor  math
a   10   20    90
c   50   40    20
b   30   40    50
d   70   80    70 

   eng  kor  math
a   10   20    90
c   50   40    20
b   30   40    50
d   70   80    70


In [178]:
print(df, '\n')

print(df.sort_index())

   eng  kor  math
a   10   20    90
c   50   40    20
b   30   40    50
d   70   80    70 

   eng  kor  math
a   10   20    90
b   30   40    50
c   50   40    20
d   70   80    70
