In [1]:
import numpy as np
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)

print(arr1)
print(data1)

data2 = [[1,2,3,4], [5,6,7,8]]
arr2 = np.array(data2)
print(arr2)

print(arr2.shape)
print(arr2.dtype)



[6.  7.5 8.  0.  1. ]
[6, 7.5, 8, 0, 1]
[[1 2 3 4]
 [5 6 7 8]]
(2, 4)
int32


In [2]:
import numpy as np

arr1 = np.arange(1, 10, 2)
print(arr1)

arr2 = np.linspace(-2, 2, 4)
print(arr2)

arr3 = np.ones([2, 3])
print(arr3)

arr4 = np.zeros([2, 3])
print(arr4)

[1 3 5 7 9]
[-2.         -0.66666667  0.66666667  2.        ]
[[1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]]


In [4]:
import numpy as np

arr = np.array([[1., 2., 3.], [4., 5., 6.]])
print(arr)
print(arr / 2)
print(arr * arr)
print(arr - arr)

arr2= np.array([[0., 4., 1.], [7., 2., 12.]])
print(arr2 > arr)

[[1. 2. 3.]
 [4. 5. 6.]]
[[0.5 1.  1.5]
 [2.  2.5 3. ]]
[[ 1.  4.  9.]
 [16. 25. 36.]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[False  True False]
 [ True False  True]]


In [11]:
import numpy as np

arr = np.arange(10)
print(arr[5])
print(arr[5:8])
arr[5:8] = 12
print(arr)


arr = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(arr[:2])
print(arr[:2, 1:])

arr2 = np.array([[True, False, False], [True, False, True], [False, True, False]])
print(arr[arr2])

5
[5 6 7]
[ 0  1  2  3  4 12 12 12  8  9]
[[1 2 3]
 [4 5 6]]
[[2 3]
 [5 6]]
[1 4 6 8]


In [13]:
# 재형성
# ndarray는 데이터를 복사하지 않고 다른 모양으로 바꿀수 있는 reshape()를 제공한다.
import numpy as np

arr = np.arange(8)
arr2 = arr.reshape((4, 2))
print(arr2)

arr3 = arr.reshape((4, 2)).reshape((2, 4))
print(arr3)

[[0 1]
 [2 3]
 [4 5]
 [6 7]]
[[0 1 2 3]
 [4 5 6 7]]


In [14]:
# 정렬
import numpy as np
arr = np.array([2,5,9,1,3,7])
arr.sort()
print(arr)

[1 2 3 5 7 9]


In [15]:
import numpy as np
np.random.seed(123)
data1 = np.random.randn(4, 5)
data1

array([[-1.0856306 ,  0.99734545,  0.2829785 , -1.50629471, -0.57860025],
       [ 1.65143654, -2.42667924, -0.42891263,  1.26593626, -0.8667404 ],
       [-0.67888615, -0.09470897,  1.49138963, -0.638902  , -0.44398196],
       [-0.43435128,  2.20593008,  2.18678609,  1.0040539 ,  0.3861864 ]])

In [21]:
import numpy as np
arr = np.random.randn(5, 4)
print(arr)
print('mean', np.mean(arr))
print('sum', arr.sum())

# 축에따른 평균과 합
print(arr.mean(axis = 1))
print(arr.sum(axis = 0))

# 누적합
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7])
print(arr.cumsum())

# 축의 따른 누적합
arr = np.array([[0, 1, 2],
               [3, 4, 5],
               [6, 7, 8]])

print(arr.cumsum(axis = 0))
print(arr.cumprod(axis = 1))

[[ 0.64205469 -1.97788793  0.71226464  2.59830393]
 [-0.02462598  0.03414213  0.17954948 -1.86197571]
 [ 0.42614664 -1.60540974 -0.4276796   1.24286955]
 [-0.73521696  0.50124899  1.01273905  0.27874086]
 [-1.37094847 -0.33247528  1.95941134 -2.02504576]]
mean -0.03868970667823831
sum -0.7737941335647662
[ 0.49368383 -0.41822752 -0.09101829  0.26437799 -0.44226454]
[-1.06259008 -3.38038183  3.43628492  0.23289286]
[ 0  1  3  6 10 15 21 28]
[[ 0  1  2]
 [ 3  5  7]
 [ 9 12 15]]
[[  0   0   0]
 [  3  12  60]
 [  6  42 336]]
